apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-klg4
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-vdkj-tenant/rhtap-demo-app/hacbs-test-project-klg4@sha256:88162a35833c82737fc94b0ca267d747db1851926080c0a951f907468a9ceef9
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
